version: "3.9"

services:
#─────────────────────────  DATABASE  ─────────────────────────
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bindiq_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bindiq_db"]
      interval: 5s
      timeout: 5s
      retries: 5

#─────────────────────────  BACKEND  ──────────────────────────
  backend:
    build: ./backend
    command: >
      python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000 
    environment:
      # Local package path & DB connection string
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/bindiq_db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend              # Hot‑reload your code
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"

#─────────────────────────  FRONTEND  ─────────────────────────
  frontend:
    build: ./frontend
    command: >
      sh -c "npm install --force &&
             npm run dev -- --host 0.0.0.0 --port 5173"
    environment:
      - ROLLUP_NO_NATIVE=1
      - VITE_NO_NATIVE=1
      # 👇 Browser can reach localhost:8000 on the host machine
      - VITE_API_URL=http://localhost:8000
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./frontend:/app                     # Live‑reload React code
      - /app/node_modules                   # Keep node_modules inside container
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
